version: "3"
services:
  elasticsearchApache:
    image: elasticsearch:7.6.2
    container_name: elasticsearchApache
    hostname: elasticsearchApache
    restart: always
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - dockerelk
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstashApache:
    image: logstash:7.6.2
    container_name: logstashApache
    hostname: logstashApache
    ports:
      - 9600:9600
      - 8089:8089
    restart: always
    links:
      - elasticsearchApache:elasticsearchApache
    depends_on:
      - elasticsearchApache
    networks:
      - dockerelk
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./web_server_logs/logstash-apache.conf:/usr/share/logstash/pipeline/logstash-apache.conf
      - ./data/apache_logs.txt:/data/apache_logs.txt 

  kibanaApache:
    image: kibana:7.6.2
    container_name: kibanaApache
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearchApache:9200
    ports:
      - "5601:5601"
    networks:
      - dockerelk
    depends_on:
      - elasticsearchApache

networks:
  dockerelk:
    driver: bridge
  
volumes:
  apache_logs.txt: